### ISSUE TITLE
Build Error - caused by 'no release file' error

### ISSUE THREAD

**Issue by alexbeeston** [heremaps/tin-terrain#73]
Running build-docker.sh results in the following output:

```
Sending build context to Docker daemon 10.44 MB
Step 1/18 : FROM ubuntu:18.10
 ---> 9dc19675e327
Step 2/18 : RUN apt-get update
 ---> Running in 17c69c3ada81

Ign:1 http://archive.ubuntu.com/ubuntu cosmic InRelease
Ign:2 http://security.ubuntu.com/ubuntu cosmic-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu cosmic-updates InRelease
Err:4 http://security.ubuntu.com/ubuntu cosmic-security Release
  404  Not Found [IP: 91.189.88.142 80]
Ign:5 http://archive.ubuntu.com/ubuntu cosmic-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu cosmic Release
  404  Not Found [IP: 91.189.88.142 80]
Err:7 http://archive.ubuntu.com/ubuntu cosmic-updates Release
  404  Not Found [IP: 91.189.88.142 80]
Err:8 http://archive.ubuntu.com/ubuntu cosmic-backports Release
  404  Not Found [IP: 91.189.88.142 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu cosmic-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-backports Release' does not have a Release file.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

I was able to build the image successfully by replacing line 1 in Dockerfile with "FROM ubuntu" (just removed the versioning). Is this an error from my end, or is this something that needs to be updated in the repository?

**Comment by fnicollet** [comment]
hello @alexbeeston and thanks for providing the solution for this issue, it also worked in my case, I guess it should be fixed in the source code.
I would provide a Pull Request but it seems that this project hasn't been accepting any for a little over a year now ...

**Comment by FranzHeubach** [comment]
I had this issue as well. Looked into it a bit. The `ubuntu:18.10` image has the described bug when trying to run `apt-get update`. The image for the LTS version of ubuntu 18 does not (`ubuntu:18.04`). I switched the version number and the issue is resolved as suggested.

**Comment by Bellkross** [comment]
Please consider adding this pull request. The problem still remains and this commit helped me to fix it.

**Comment by qiyan98** [comment]
> Please consider adding this pull request. The problem still remains and this commit helped me to fix it.

Fully agreed!

**Comment by ZackOfAllTrades** [comment]
oh bummer, I hit this issues as well, still not fixed 3/22/2022
